language: cpp
sudo: required
matrix:
  include:
    - name: Ubuntu Bionic LTS GCC
      os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="gcc -v && g++ -v"
    - name: Ubuntu Bionic LTS Clang
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang-7.0 && clang-7.0 --version"
before_install:
  - eval "${MATRIX_EVAL}"
  - chmod +x fetch-deps
  - ./fetch-deps
script:
  - make
  - make test
before_script:
  - mkdir build
  - cd build
  - cmake ..
notifications:
  email: false