language: cpp
sudo: required
git:
  depth: 1
matrix:
  include:
    - name: Ubuntu Bionic LTS
      os: linux
      dist: bionic
      compiler:
        - clang
        - gcc
      before_install:
        - chmod +x fetch-deps
        - ./fetch-deps
      before_script:
        - mkdir build
        - cd build
        - cmake ..
      script:
        - make
        - make test
notifications:
  email: false