language: cpp
sudo: required
matrix:
  include:
    - name: MacOS Xcode 11
      os: osx
      osx_image: xcode11
before_install:
  - chmod +x fetch-deps
  - ./fetch-deps
script:
  - make
  - make test
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
notifications:
  email: false