language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - chmod +x fetch-deps && ./fetch-deps
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make && make test