language: cpp
sudo: required
matrix:
  include:
    - name: Ubuntu Bionic LTS GCC
      os: linux
      dist: bionic
      compiler: gcc
    - name: Ubuntu Bionic LTS Clang
      os: linux
      dist: bionic
      compiler: clang
before_install:
  - chmod +x fetch-deps
  - ./fetch-deps
script:
  - make
  - make test
before_script:
  - mkdir build
  - cd build
  - cmake ..
notifications:
  email: false