language: cpp
sudo: required
git:
  depth: 1
matrix:
  include:
    - name: Ubuntu Bionic LTS
      os: linux
      dist: bionic
      compiler:
        - clang
        - gcc
      before_install:
        - chmod +x fetch-deps
        - ./fetch-deps
      before_script:
        - mkdir build
        - cd build
        - cmake ..
      script:
        - make
        - make test
    - name: Windows Server 1803
      os: windows
      before_install:
        - choco install ninja nuget.commandline
        - fetch-deps
      before_script:
        - mkdir build
        - cd build
        - cmake -G Ninja ..
      script:
        - ninja
        - ninja test
notifications:
  email: false