shallow_clone: true
image: Visual Studio 2019
clone_depth: 3
platform: x64
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - cd C:\projects\openhoi
  - fetch-deps
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja ..
  - ninja
  - ninja test
notifications:
  - provider: Email 
    on_build_success: false 
    on_build_failure: false 
    on_build_status_changed: false