name: openhoi
version: '0.0.1'
base: core18
summary: openhoi is a free, open-source multiplayer 4X game
description: |
  A free, open-source, multiplayer 4X game inspired by the
  great titles crafted by Paradox Interactive.
grade: devel
confinement: devmode
parts:
  my-part:
    plugin: nil
